from typing import Any, Optional

def calling_function(skip: Any=...) -> Optional[str]: ...
def last_frames(): ...
def last_stack_frame(frame_num: int = ...): ...
def calling_module(skip: Any=...) -> Optional[str]: ...
def caller_name(skip: Any=...) -> Optional[str]: ...
