from datetime import datetime as datetime
from os.path import basename as basename
from typing import Any, Optional

BASE_DIR: Any
VERSION_FILE: Any
EXTRAS_FOLDER: str
DEFAULT_CACHE_TIMEOUT: int
REDIS_HOST: str
REDIS_PORT: int
REDIS_DB: int
MEMCACHED_HOST: str
MEMCACHED_PORT: int
search_geoip: Any
GEOIP_DIR: Any
GEOASN_NAME: Any
GEOCITY_NAME: Any
GEOCOUNTRY_NAME: Any
GEOASN_DETECTED: Any
GEOCITY_DETECTED: Any
GEOCOUNTRY_DETECTED: Any
GEOCITY: Any
GEOASN: Any
GEOCOUNTRY: Any
TERMBIN_HOST: Any
TERMBIN_PORT: Any
CHECK_CONNECTIVITY: bool
HAS_WORKING_V4: Optional[bool]
HAS_WORKING_V6: Optional[bool]
SSL_VERIFY_CERT: bool
SSL_VERIFY_HOSTNAME: bool
DEFAULT_USER_AGENT: str
NET_CHECK_TIMEOUT: int
NET_CHECK_HOST_COUNT: int
NET_CHECK_HOST_COUNT_TRY: int
V4_TEST_HOSTS: Any
V6_TEST_HOSTS: Any
DEFAULT_SOCKET_TIMEOUT: int
DEFAULT_READ_TIMEOUT: Any
DEFAULT_WRITE_TIMEOUT: Any
SQLITE_APP_DB_NAME: Any
SQLITE_APP_DB_FOLDER: Any
