dist: bionic
services:
  - redis-server
language: python
cache: pip
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.7-dev"
  - "3.8-dev"
  - "nightly"
before_install:
  - sudo apt-get update -qy
  - sudo apt-get install -qy iputils-ping
install:
  - pip install -U '.[dev]'
script: pytest --cov=./privex -rxXs -v
after_success:
  - codecov
