dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
  - "3.7-dev"
  - "3.8-dev"
  - "nightly"
install:
  - pip install -r docs/requirements.txt
  - pip install .
service:
  - redis-server
script: pytest tests.py
