dist: bionic
services:
  - redis-server
language: python
env:
  - CODECOV_TOKEN="e309d317-ca30-4c79-a01c-f4dc7c60e471"
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.7-dev"
  - "3.8-dev"
  - "nightly"
before_install:
  - sudo apt-get update -qy
  - sudo apt-get install -qy iputils-ping
install:
  - pip install -r docs/requirements.txt
  - pip install .
script: pytest --cov=./privex -v
after_success:
  - codecov
