from ipaddress import IPv4Address
from privex.helpers.types import IP_OR_STR
from typing import Any, Optional, Union

def ip_is_v4(ip: str) -> bool: ...
def ip_is_v6(ip: str) -> bool: ...
def ping(ip: str, timeout: int=...) -> bool: ...

IPV4_ALIASES: Any
IPV6_ALIASES: Any

def ip_ver_to_int(ver: Union[str, int]) -> int: ...
def sock_ver(version: Any) -> Optional[int]: ...
ip_ver_to_sock = sock_ver

def is_ip(addr: str, version: int=...) -> Any: ...
def sock_validate_ip(addr: IP_OR_STR, version: int, throw: Any=...) -> Optional[Union[IPv4Address, IPv4Address]]: ...
