from privex.helpers import byteify as byteify
from typing import Union

def is_base64(sb: Union[str, bytes], urlsafe: bool=...) -> bool: ...
def auto_b64decode(data: Union[str, bytes], urlsafe: bool=...) -> bytes: ...
