from privex.helpers.settings import EXTRAS_FOLDER as EXTRAS_FOLDER
from typing import Any, Dict, Union

log: Any

def strip_comments(l: str) -> str: ...
def pip_requirement(req: str) -> list: ...
def reqs(*f: str) -> list: ...
def extras(*p: Any) -> list: ...
def extras_require(extra: Union[list, set, tuple]) -> Dict[str, list]: ...
